1732492392998	Sync.LogManager	DEBUG	Flushing file log
1732492393016	Sync.LogManager	DEBUG	Log cleanup threshold time: 1731628393016
1732492393034	Sync.LogManager	DEBUG	Done deleting files.
1732492398187	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1732492421248	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1732492421248	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1732492421252	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1732492421256	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1732492427778	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1732492429642	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1732492429642	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1732492429646	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1732492429648	Sync.Service	DEBUG	User-Agent: Firefox/134.0a1 (Linux x86_64) FxSync/1.136.0.20241118092854.desktop
1732492429648	Sync.Service	INFO	Starting sync at 2024-11-25 00:53:49 in browser session 9TU_33ega8ND
1732492429648	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1732492429655	Sync.Status	INFO	Resetting Status.
1732492429655	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1732492429656	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1732492429695	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/264523642/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1732492429695	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1732492429695	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1732492429695	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1732492429696	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1732492429701	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
